---
- name: installing adduser, libfontconfig1 packages
  apt:
    pkg:
    - adduser
    - libfontconfig1

- name: Install grafana.deb package
  apt:
    deb: https://dl.grafana.com/oss/release/grafana_7.2.2_amd64.deb

- name: reload daemon and making sure grafana-server service is running
  systemd:
    state: started
    name: grafana-server.service
    daemon_reload: yes
    enabled: yes